FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
# Copy folder prisma agar bisa generate client
COPY prisma ./prisma/ 

RUN npm ci
# Penting agar Prisma Client tersedia di dalam container
RUN npx prisma generate 

COPY . .

RUN npm run build

EXPOSE 3000

# Perhatikan perubahan dari .ts ke .js
CMD [ "node", "dist/main.js" ]